-- SQL Schema for Proyecto Temis

-- 1. Tabla de Perfiles (Usuarios registrados)
CREATE TABLE IF NOT EXISTS perfiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    nombre TEXT,
    creditos INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabla de Uso por IP (Control de Rate Limit para invitados)
CREATE TABLE IF NOT EXISTS uso_por_ip (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip TEXT UNIQUE NOT NULL,
    conteo INTEGER DEFAULT 1,
    ultima_consulta TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Tabla de Pagos Reportados (Reportes de Pago Móvil)
CREATE TABLE IF NOT EXISTS pagos_reportados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_perfil UUID REFERENCES perfiles(id),
    referencia TEXT NOT NULL,
    fecha_pago DATE NOT NULL,
    monto NUMERIC NOT NULL,
    moneda TEXT DEFAULT 'Bs',
    validado BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS (Row Level Security) - Ejemplo básico
ALTER TABLE perfiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Usuarios pueden ver su propio perfil" ON perfiles FOR SELECT USING (auth.uid() = id);

ALTER TABLE pagos_reportados ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Usuarios pueden reportar sus pagos" ON pagos_reportados FOR INSERT WITH CHECK (auth.uid() = id_perfil);
